version: '3.7'

services:
    postgrest:
        image: postgrest/postgrest
        ports:
            - '3000:3000'
        environment:
            PGRST_DB_URI: postgres://florian@localhost:5432/florian
            PGRST_DB_SCHEMA: cardio
            PGRST_DB_ANON_ROLE: web_anon
        network_mode: host

    swagger:
        image: swaggerapi/swagger-ui
        ports:
          - "0:8080"
        environment:
          API_URL: http://localhost:3000/
